---
title: "fetch_data: mom-baby link"
author: "Dominick Lemas"
date: "11/09/2024"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
---

```{r, include=FALSE}
# ****************************************************************************** #
#                                  Project Overview                               
# ****************************************************************************** #

# Author:            Dominick Lemas
# Start Date:        November 09, 2024
# Last Modified:     
# IRB:               UFHealth Early Life Exposures and Pediatric Outcomes (IRB201601899)

# Software Versions:
# - R version:       4.0.3 (2020-10-10)
# - RStudio version: 1.3.1073

# ****************************************************************************** #
#                                  Description                                    
# ****************************************************************************** #

# PLAN:
# - Access flat files on the shared drive
# - Pull, format, and clean data for downstream analyses

# NOTE:
# - Ensure VPN is active to access the shared drive

# OBJECTIVE:
# - Export mom-baby link as an RDA file

# ****************************************************************************** #
#                                  Libraries                                      
# ****************************************************************************** #

# directory
working_dir="C:/Users/djlemas/OneDrive/Documents/ehr-database"

# Load required packages
library(tidyverse)   # Comprehensive R package for data science
library(lubridate)   # Simplifies date and time manipulation
source(paste0(working_dir,"/code/functions/all_functions.R"))
# source("C:/Users/djlemas/Documents/GitHub/ehr-cancer-outcomes/code/functions/all_functions.R")

```


```{r, include=FALSE, message=FALSE, warning=FALSE}
# **************************************************************************** #
#                          baby_mom_link Data Import                           
# **************************************************************************** #

# Task:
# - Import and process baby-mom link data.
# - Ensure consistent formatting of identifiers.
# - Prepare data for downstream analysis.

# Dataset Summary:
# - Rows:            28,530
# - Columns:         3
# - Unique Mom IDs:  22,075
# - Unique Infant IDs: 28,530
# - Repeats:         1
# - ICD9/10:         NA

# Data Directory:
data_file_name <- "mom_baby_link.rda"
data_dir <- paste0("V:/FACULTY/DJLEMAS/EHR_Data/processed/10year_data/")
data_import_path <- paste0(data_dir, data_file_name)

# Data Import and Transformation:
mom_baby_link_tmp <- load(data_import_path) 


```

