---
title: "fetch_data: prenatal-bmi (February 2025)"
author: "Dominick Lemas"
date: "11/07/2024"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
---

```{r, include=FALSE, echo=FALSE}

# **************************************************************************** #
#                           Project Overview                                   #
# **************************************************************************** #

# Author:            Dominick Lemas
# Start Date:        November 06, 2024
# Last Modified:     February 18, 2025
# IRB:               UFHealth Early Life Exposures and Pediatric Outcomes (IRB201601899)

# R Version:         4.0.3 (2020-10-10)
# RStudio Version:   1.3.1073

# **************************************************************************** #
#                           Project Description                                #
# **************************************************************************** #

# Purpose:
# This script aims to access flat files stored on the shared drive, 
# pull, format, and clean the data for downstream analysis.

# Requirements:
# - VPN must be active for remote access to the shared drive.
# - R packages: tidyverse, lubridate.

# Objective:
# Export cleaned prenatal BMI data as an .rda file for subsequent analyses.

# Plan:
# 1. Access flat files stored on the shared drive.
# 2. Load the data into R.
# 3. Perform data formatting and cleaning.
# 4. Save the cleaned data as an .rda file.

# Notes:
# - Ensure that you have the necessary permissions to access the shared drive.
# - Review the data for inconsistencies before saving the final .rda file.

# **************************************************************************** #
#                           Libraries                                          #
# **************************************************************************** #

library(tidyverse)   # Comprehensive collection of data manipulation and visualization tools
library(lubridate)   # Functions to work with date and time objects

# End of Script
##############################################################################
```

```{r, include=FALSE, message=FALSE, warning=FALSE}

# ----------------------------------------------------------------------- #
# Step 1: Pull Data
# ----------------------------------------------------------------------- #

# Dataset Summary:
# - Rows:              182,318      
# - Columns:           4 
# - Unique Mom IDs:    16,898
# - Unique Infant IDs: NA
# - Repeat:            1
# - ICD9/10 Codes:     NA

# Data Directory:
# -----------------
# The dataset file and its directory path.
data_file_name <- "mom_BMI_prenatals.csv"
data_dir <- paste0("V:/FACULTY/DJLEMAS/EHR_Data/raw/READ_ONLY_DATASETS/10year_data/2021/dataset_09_2021/mom_data/")
data_import_path <- paste0(data_dir, data_file_name)

prenatal_bmi_mom_tmp <- read_csv(data_import_path, col_types = cols()) %>%
  rename(
    part_id_mom_tmp = `Deidentified_mom_ID`, 
    encounter_type = `Encounter Type`,
    prenatal_bmi_kgm2 = `Last Stamped BMI on encounter`, 
    prenatal_bmi_date = `Last Stamped BMI on encounter datetime`
  ) %>%
  mutate(
    prenatal_bmi_date = ymd_hms(prenatal_bmi_date),
    part_id_mom = paste0("mom-", part_id_mom_tmp)
  ) %>%
  select(-part_id_mom_tmp) %>% 
  select(part_id_mom, everything())

# End of Script
##############################################################################
```

```{r, include=FALSE, message=FALSE, warning=FALSE}

# ----------------------------------------------------------------------- #
# Step 2: load mom-baby link data
# ----------------------------------------------------------------------- #
load("V:/FACULTY/DJLEMAS/EHR_Data/processed/10year_data/mom_baby_link_02_2025.rda") 

# ----------------------------------------------------------------------- #
# Step 3: merge data with mom-baby link and compute derived variables
# ----------------------------------------------------------------------- #
prenatal_bmi_mom_tmp2 <- full_join(prenatal_bmi_mom_tmp, mom_baby_link_02_2025, by = "part_id_mom") %>%
  
  # Task 2.1: Retain only records with valid prenatal BMI dates
  drop_na(prenatal_bmi_date) %>%
  
  # Task 2.2: Format Date Fields
  # Convert the datetime columns to Date format for consistent processing
  mutate(
    prenatal_bmi_date = as_date(prenatal_bmi_date),
    part_dob_infant = as_date(part_dob_infant)
  ) %>%
  
  # Task 2.3: Calculate Derived Variables
  # Compute the interval (in days) between prenatal BMI measurement and infant's date of birth
  mutate(
    dx2delivery_days = as.numeric(prenatal_bmi_date - part_dob_infant)
  ) 

# rename
prenatal_bmi_mom_02_2025=prenatal_bmi_mom_tmp2

```


```{r, message=FALSE}
# ----------------------------------------------------------------------- #
# Step 4: export to sharedrive
# ----------------------------------------------------------------------- #

## EXPORT to Sharedrive
file_name="prenatal_bmi_mom_02_2025.rda"
data_export_directory=paste0("V:/FACULTY/DJLEMAS/EHR_Data/processed/10year_data/") 
data_export_path=paste0(data_export_directory,file_name)
prenatal_bmi_mom_02_2025 %>% save(prenatal_bmi_mom_02_2025, file=data_export_path)


```
