---
title: "fetch_data: infant icd codes (October 2025; Gainesville)"
author: "Dominick Lemas"
date: "10/23/2025"
output: html_document

---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:           Dominick Lemas
# Start Date:       Nov 06, 2024 
# Last Modified:    Oct 23, 2025  
# IRB:              IRB201601899 
#
# Software Versions:
# - R version:       4.0.3 (2020-10-10)
# - RStudio version: 1.3.1073

# **************************************************************************** #
# ***************                Description                  
# **************************************************************************** #

# PLAN:
# - Access flat files on the shared drive
# - Pull, format, and clean data for downstream analyses

# NOTE:
# - Ensure VPN is active to access the shared drive

# OBJECTIVE:
# - Export ICD9/10 codes an RDA file

# **************************************************************************** #
# ***************                Library                       
# **************************************************************************** #

library(tidyverse)

# directory
 working_dir="C:/Users/djlemas/Documents/GitHub/ehr-database"


```

```{r, message=FALSE}

# **************************************************************************** #
#    GAINESVILLE:         multiple.csv files                         
# **************************************************************************** #

# ----------------------------------------------------------------------- #
# Step 1: Pull Data
# ----------------------------------------------------------------------- #

# column-types
#-------------
col_types <- readr::cols(
      Deidentified_baby_ID  = readr::col_factor(),
      `Diagnosis Type` = readr::col_factor(),
      `Diagnosis Code`	 = readr::col_factor(),
      `Diagnosis Description`  = readr::col_character(),
      `Diagnosis Start Date` = readr::col_date()
     )

# 10year_data>2021>dataset_09_2021>baby_data

data_directory="V:/FACULTY/DJLEMAS/EHR_Data/raw/READ_ONLY_DATASETS/10year_data/"

# baby_asthma
#----------------
  file="baby_asthma"
  path=paste0(data_directory,"2021/dataset_09_2021/baby_data/",file,".csv")
  baby_asthma=read_csv(file=path, col_types=col_types) %>%
    mutate(dx_category="asthma") %>%
    select(Deidentified_baby_ID,dx_category,everything())

# baby_ear_infection
#----------------
  file="baby_ear_infection"
  path=paste0(data_directory,"2021/dataset_09_2021/baby_data/",file,".csv")
  baby_ear_infection=read_csv(file=path, col_types=col_types) %>%
    mutate(dx_category="ear_infection") %>%
    select(Deidentified_baby_ID,dx_category,everything())

# baby_eczema
#----------------
  file="baby_eczema"
  path=paste0(data_directory,"2021/dataset_09_2021/baby_data/",file,".csv")
  baby_eczema=read_csv(file=path, col_types=col_types) %>%
    mutate(dx_category="eczema") %>%
    select(Deidentified_baby_ID,dx_category,everything())
  
# baby_food_allergy
#----------------
  file="baby_food_allergy"
  path=paste0(data_directory,"2021/dataset_09_2021/baby_data/",file,".csv")
  baby_food_allergy=read_csv(file=path, col_types=col_types) %>%
    mutate(dx_category="food_allergy") %>%
    select(Deidentified_baby_ID,dx_category,everything())

# baby_hemangonia
#----------------
  file="baby_hemangonia"
  path=paste0(data_directory,"2021/dataset_09_2021/baby_data/",file,".csv")
  baby_hemangonia=read_csv(file=path, col_types=col_types) %>%
    mutate(dx_category="hemangonia") %>%
    select(Deidentified_baby_ID,dx_category,everything())
  
# baby_nevus
#----------------
  file="baby_nevus"
  path=paste0(data_directory,"2021/dataset_09_2021/baby_data/",file,".csv")
  baby_nevus=read_csv(file=path, col_types=col_types) %>%
    mutate(dx_category="nevus") %>%
    select(Deidentified_baby_ID,dx_category,everything())

# baby_obesity
#----------------
  file="baby_obesity"
  path=paste0(data_directory,"2021/dataset_09_2021/baby_data/",file,".csv")
  baby_obesity=read_csv(file=path, col_types=col_types) %>%
    mutate(dx_category="obesity") %>%
    select(Deidentified_baby_ID,dx_category,everything())  
  
# baby_sebor
#----------------
  file="baby_sebor"
  path=paste0(data_directory,"2021/dataset_09_2021/baby_data/",file,".csv")
  baby_sebor=read_csv(file=path, col_types=col_types) %>%
    mutate(dx_category="sebor") %>%
    select(Deidentified_baby_ID,dx_category,everything())  

# baby_toxicum
#----------------
  file="baby_toxicum"
  path=paste0(data_directory,"2021/dataset_09_2021/baby_data/",file,".csv")
  baby_toxicum=read_csv(file=path, col_types=col_types) %>%
    mutate(dx_category="toxicum") %>%
    select(Deidentified_baby_ID,dx_category,everything())
  
# neonatal_defects_release
#----------------
  file="neonatal_defects_release"
  path=paste0(data_directory,"2022/dataset_07_2022/",file,".csv")
  neonatal_defects_release=read_csv(file=path, col_types=col_types) %>%
    mutate(dx_category="neonatal_defects") %>%
    select(Deidentified_baby_ID,dx_category,everything()) 
  
# combine infant ICD9/10 code
wellbaby_icd_codes_infant_tmp=rbind(baby_asthma,baby_ear_infection,baby_eczema,baby_food_allergy,baby_hemangonia,baby_nevus,baby_obesity,baby_sebor,baby_toxicum,neonatal_defects_release) %>%
    rename(part_id_infant_tmp=Deidentified_baby_ID,
           dx_date="Diagnosis Start Date",
           dx_code="Diagnosis Code",
           dx_descrip="Diagnosis Description",
           dx_type="Diagnosis Type") %>%
  mutate(part_id_infant=paste0("infant-",part_id_infant_tmp)) %>%
  select(-part_id_infant_tmp) %>% 
  select(part_id_infant,dx_category,everything()) %>%
  mutate(part_id_infant=paste0("GNV-",part_id_infant))

```

```{r, include=FALSE, message=FALSE, warning=FALSE}

# ----------------------------------------------------------------------- #
# Step 2: load mom-baby link data
# ----------------------------------------------------------------------- #
# load("V:/FACULTY/DJLEMAS/EHR_Data/processed/READ_ONLY_DATASETS/10year_data/mom_baby_link_ALL_20250418.rda")

data_file_name <- "mom_baby_link_ALL_20251023.rda"
data_dir <- paste0(working_dir,"/data/ready/")
data_import_path <- paste0(data_dir, data_file_name)
load(data_import_path)

mom_baby_link_tmp=mom_baby_link_ALL %>%
  select(part_id_infant, delivery_id, part_dob_infant)

# ----------------------------------------------------------------------- #
# Step 3: merge data with mom-baby link and compute derived variables
# ----------------------------------------------------------------------- #
wellbaby_icd_codes_infant_tmp2 =left_join(wellbaby_icd_codes_infant_tmp, mom_baby_link_tmp , by = "part_id_infant") %>%
  mutate(
          # Compute days-to-diagnosis relative to date-of-birth
        dx2delivery_days = as.numeric(ymd(dx_date) - ymd(part_dob_infant))) 

# rename
GNV_infant_icd_codes_10_2025=wellbaby_icd_codes_infant_tmp2 %>%
  select(part_id_infant,delivery_id,part_dob_infant,dx2delivery_days,everything())

```

```{r, message=FALSE}
# ----------------------------------------------------------------------- #
# Step 3: export to sharedrive
# ----------------------------------------------------------------------- #

## EXPORT 
file_name="GNV_infant_icd_codes"
timestamp <- format(Sys.time(), "_%Y%m%d")
file_name_path=paste0(file_name,timestamp,".rda")

# Define export directories
shared_dir <- "V:/FACULTY/DJLEMAS/EHR_Data/processed/READ_ONLY_DATASETS/10year_data/GNV/"
local_dir  <- file.path(working_dir, "data", "ready")

# Ensure local directory exists
if (!dir.exists(local_dir)) dir.create(local_dir, recursive = TRUE)

# Construct full export paths
shared_path <- file.path(shared_dir, file_name_path)
local_path  <- file.path(local_dir, file_name_path)

# Save to shared drive
save(GNV_infant_icd_codes_10_2025, file = shared_path)

# Save locally
save(GNV_infant_icd_codes_10_2025, file = local_path)

message("Data successfully exported to:")
message(" - Shared drive: ", shared_path)
message(" - Local folder: ", local_path)

```
