---
title: "fetch_data: all maternal codes (October 2025; Gainesville)"
author: "Dominick Lemas"
date: "10/23/2025"
output: html_document
---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              
# **************************************************************************** #

# Author:            Dominick Lems
# Start Date:        November 06, 2024 
# Last Modified:     October 23, 2025
# IRB:         IRB protocol IRB201601899 
#
# Software Versions:
# - R version:       4.0.3 (2020-10-10)
# - RStudio version: 1.3.1073

# **************************************************************************** #
# ***************                Description                   
# **************************************************************************** #
# PLAN: Access flat files on sharedrive, pull/format/clean data for downstream.
# NOTE: vpn must be active
# OBJECTIVE: Export all prenatal ht/wt as rda file.

```

```{r, include=FALSE, echo=FALSE}

# **************************************************************************** #
# ***************                Libraries                     *************** #
# **************************************************************************** #

library(tidyverse)
library(lubridate)

# directory
 working_dir="C:/Users/djlemas/Documents/GitHub/ehr-database"

```


```{r, include=FALSE, message=FALSE, warning=FALSE}

# ----------------------------------------------------------------------- #
# Step 1: Pull Data
# ----------------------------------------------------------------------- #
# rows:            182318      
# cols:            4 
# unique baby id:  16898
# repeat:          1
# ICD9/10:         NA

# data-directory
#-----------------
data_file_name="mom_height_weight_prenatals.csv"
data_dir=paste0("V:/FACULTY/DJLEMAS/EHR_Data/raw/READ_ONLY_DATASETS/10year_data/2021/dataset_09_2021/mom_data/")
data_import_path=paste0(data_dir,data_file_name)

# read data
prenatal_htwt_mom_tmp=read_csv(data_import_path, col_types = cols()) %>%
  rename(part_id_mom_tmp = `Deidentified_mom_ID`, 
         encounter_type = `Encounter Type`,
         encounter_date= `Height&Weight Datetime`,
         prenatal_wt_lbs_mom = `Weight (lb)`,
         prenatal_ht_in_mom = `Height (in)`) %>%
  mutate(part_id_mom=paste0("mom-",part_id_mom_tmp)) %>%
  select(-part_id_mom_tmp) %>% 
  select(part_id_mom, everything()) %>%
  mutate(part_id_mom=paste0("GNV-",part_id_mom))

```


```{r, include=FALSE, message=FALSE, warning=FALSE}

# ----------------------------------------------------------------------- #
# Step 2: load mom-baby link data
# ----------------------------------------------------------------------- #
# load("V:/FACULTY/DJLEMAS/EHR_Data/processed/10year_data/mom_baby_link_02_2025.rda") 
data_file_name <- "mom_baby_link_ALL_20251023.rda"
data_dir <- paste0(working_dir,"/data/ready/")
data_import_path <- paste0(data_dir, data_file_name)
load(data_import_path)

# ----------------------------------------------------------------------- #
# Step 3: merge data with mom-baby link and compute derived variables
# ----------------------------------------------------------------------- #
prenatal_htwt_mom_tmp2 <- full_join(prenatal_htwt_mom_tmp, mom_baby_link_ALL, by = "part_id_mom", relationship = "many-to-many") %>%
  mutate(
    encounter_date = as_date(encounter_date),  # Ensure proper Date format
    part_dob_infant = as_date(part_dob_infant),  # Ensure proper Date format

    # Compute days-to-diagnosis relative to date-of-birth
    dx2delivery_days = if_else(
      complete.cases(encounter_date, part_dob_infant),
      as.numeric(difftime(encounter_date, part_dob_infant, units = "days")), 
      NA_real_  # Preserve NA values
    )
  )

# rename
GNV_mom_prenatal_htwt_10_2025=prenatal_htwt_mom_tmp2

```


```{r, message=FALSE}

# ----------------------------------------------------------------------- #
# Step 4: export to sharedrive
# ----------------------------------------------------------------------- #

## EXPORT 
file_name="GNV_mom_prenatal_htwt"
timestamp <- format(Sys.time(), "_%Y%m%d")
file_name_path=paste0(file_name,timestamp,".rda")

# Define export directories
shared_dir <- "V:/FACULTY/DJLEMAS/EHR_Data/processed/READ_ONLY_DATASETS/10year_data/GNV/"
local_dir  <- file.path(working_dir, "data", "ready")

# Ensure local directory exists
if (!dir.exists(local_dir)) dir.create(local_dir, recursive = TRUE)

# Construct full export paths
shared_path <- file.path(shared_dir, file_name_path)
local_path  <- file.path(local_dir, file_name_path)

# Save to shared drive
save(GNV_mom_prenatal_htwt_10_2025, file = shared_path)

# Save locally
save(GNV_mom_prenatal_htwt_10_2025, file = local_path)

message("Data successfully exported to:")
message(" - Shared drive: ", shared_path)
message(" - Local folder: ", local_path)
```