---
title: "IDR-to-Redcap: gravidity and parity"
author: "Dominick J. Lemas"
date: "01/05/2022"
output: html_document

---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick Lemas
# Start Date:        January 05, 2022 
# IRB:               IRB protocol IRB201601899 
#                    
# version: R version 4.0.3 (2020-10-10)
# version: Rstudio version Version 1.3.1073 

# **************************************************************************** #
# ***************                Objective                     *************** #
# **************************************************************************** #

#  (1) Descriptive statistics on IDR data. 
#  (2) Process IDR data. 
#  (3) Outputs for downstream import-ready files for RedCap. 


```

```{r, include=FALSE, echo=FALSE}

# **************************************************************************** #
# ***************                Libraries                     *************** #
# **************************************************************************** #

library(readxl)
library(tidyr)
library(dplyr)
library(tidyverse)
library(lubridate)
library(stringr)

```

```{r, include=FALSE, message=FALSE, warning=FALSE}
# Data Processing Notes

# IDR
release_date="Fri 9/24/2021 9:47 AM"
idr_analyst="Lei McDevitt"
idr_analyst_email="leimcdevitt@ufl.edu"

# Lemas Lab
dataprocessing_date=format(Sys.time(), "%a %b %d %X %Y")
lemaslab_analyst="Dominick Lemas"
lemaslab_analyst_email=" "
lemaslab_code="ehr-database/code/data_processing/idr2redcap_01_2022/"

```

```{r, warning=FALSE, echo=FALSE}

# **************************************************************************** #
# ***************                gravidity_release                                              
# **************************************************************************** #
# rows:       9142610
# cols:       6 
# unique id:  21997
# repeat:     1:n
# ICD9/10:    NA
# missing:    c(" ", "9999999")   

n_max=10000000
data_file_name="gravidity_release.csv"
# data_dir=paste0("~/ehr-database/data/raw/dataset_01_2022/")
data_dir=paste0("V:/FACULTY/DJLEMAS/EHR_Data/raw/dataset_01_2022/")
data_import_path=paste0(data_dir,data_file_name)

# read data
data=read_csv(data_import_path, col_types = cols()) %>%
  rename(part_id = `Deidentified_mom_ID`, 
               pregnancy_start_date_tmp=`Pregnancy Start Date`,
               gravidity=Gravidity, 
               parity=Parity)

# unique ID? Some moms had multiple babies in data set
length(unique(data$part_id)) # 22031
length(data$part_id)         # 27553

# ## FORMAT DATES
data_formatted = data %>%
  mutate(pregnancy_start_date=as.POSIXct(pregnancy_start_date_tmp, format="%m/%d/%Y")) %>% select(-pregnancy_start_date_tmp)

## FORMAT FOR REDCAP IMPORT

data_ready=data_formatted %>%
  mutate(redcap_repeat_instrument="delivery",
         redcap_event_name=tolower(paste0(year(pregnancy_start_date),"_arm_1")),
         year=year(pregnancy_start_date)) %>%
  arrange(part_id, pregnancy_start_date) %>%
  mutate(part_id=as.character(paste0("mom-",part_id))) %>%
  group_by(part_id, year) %>% mutate(redcap_repeat_instance = row_number()) %>%
  ungroup() %>% select(-year) %>%
  select("part_id","redcap_repeat_instrument","redcap_repeat_instance","redcap_event_name",everything()) 

## EXPORT FOR REDCAP

# export variables
batchSize=12000; # number of rows in single output file
data_file_name_export=paste0("mom_gravidity_",as.character(data_ready[2,2]))
# output_dir=paste0("~/ehr-database/data/processed/redcap_ready/labs/")
output_dir=paste0("V:/FACULTY/DJLEMAS/EHR_Data/processed/redcap_ready/delivery/")

data_export_path=paste0(output_dir,data_file_name_export)

# number of import files
 chunks=split(data_ready, floor(0:(nrow(data_ready)-1)/batchSize))

# export each "chunk" of redcap-ready data
 for (i in 1:length(chunks))
   { # second loop
   write.table(chunks[[i]],paste0(data_export_path,i,'.csv'),row.names=F,na = "", sep=",")
   } # end second loop        

```



