---
title: "checkData() - cancer outcomes"
author: "Dominick Lemas"
date: "11/15/2021"
output: html_document

---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:      Dominick Lemas
# Date:        Nov 17, 2020 
# Modify:      
# IRB:         UFHealth Early Life Exposures and Pediatric Outcomes (IRB201601899) 

# version: R version 4.0.2 (2020-06-22)
# version: Rstudio version Version 1.3.959 

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# PLAN: Access redcap via API and pull/format/clean data for downstream analysis.
# Note: vpn must be active

# Next steps
#- function to call the IDs and events
#- function to batch pull EHR data by year/event and combine into final dataset. 

# keyringR set up
#  https://cran.r-project.org/web/packages/keyringr/vignettes/Avoiding_plain_text_passwords_in_R_with_keyringr.html

```


```{r, message=FALSE}

# **************************************************************************** #
# ***************                Library                       *************** #
# **************************************************************************** #

library(keyringr)
library(tidyverse)
library(redcapAPI)
library(REDCapR)
library(dplyr)
library(plyr)
library(ggplot2)
```

```{r, message=FALSE}
# Windows
source("~/ehr-database/code/utils/utils.R")
source("~/ehr-database/code/utils/params.R")
api_token=get_API_token("redcap_ehr2")

# API and URL
uri='https://redcap.ctsi.ufl.edu/redcap/api/'
rcon <- redcapConnection(url=uri, token=api_token)

```

```{r, message=FALSE}

# cancer outcomes

variables=c("part_id","cancer_dx_date",
                    "cancer_dx_code","cancer_dx_descrip","cancer_dx_type",
                    "cancer_icd_code","cancer_dx_code_type")

# Specify the column types.
col_types <- readr::cols(
      part_id  = readr::col_character(),
      redcap_event_name = readr::col_factor(),
      redcap_repeat_instrument = readr::col_factor(),
      redcap_repeat_instance = readr::col_factor(),
      cancer_dx_date = readr::col_date(),
      cancer_dx_code = readr::col_factor(),
      cancer_dx_descrip  = readr::col_character(),
      cancer_dx_type = readr::col_factor(),
      cancer_icd_code = readr::col_factor(),
      cancer_dx_code_type = readr::col_factor()
     )


# Participants
records=mom_list
# event_list=c("2011_arm_1")
#batchSize=1500
#chunks=split(records, floor(1:(length(records))/batchSize))

# pull data
start_time = Sys.time()
df=getData_redcap(api_token,uri,records,variables,col_types) %>%
  filter(redcap_repeat_instrument=="diagnosis_codes") %>% as_tibble() 
end_time = Sys.time()
end_time - start_time

```

```{r, message=FALSE}

# what cancer codes do we have in dataset?

codes=df %>%
  select(cancer_dx_code) %>% unique()
  
# export unique codes

data_file_name_export="mom_cancer_codes.csv"
output_dir=paste0("V:/FACULTY/DJLEMAS/EHR_Data/output/medical_codes/")
data_export_path=paste0(output_dir,data_file_name_export)
write.table(codes,data_export_path,row.names=F,na = "", sep=",")


```


```{r, message=FALSE}

# check the redcap data: unique participants
length(unique(df$part_id))
redcap_part_id=df$part_id

# check against raw data

# file name
file_name="check_mom_cancer.rda"
#data_check_directory=paste0("~/mombaby-ehr-nlp/data/processed/redcap_check/") 
data_check_directory=paste0("V:/FACULTY/DJLEMAS/EHR_Data/processed/redcap_check/")
data_check_path=paste0(data_check_directory,file_name)
load(file=data_check_path)
raw_part_id=data_check
    
# compare raw/redcap data
length(intersect(redcap_part_id,raw_part_id))
length(outersect(redcap_part_id,raw_part_id))


# Data are equivalent
    
```

```{r, message=FALSE}

df=redcap_final

# unique participants. should be 1341 with 24249 rows
length(unique(df$part_id))
x=unique(df$part_id)

# who is not in df
outersect(x, y)




```


```{r, message=FALSE}
ggplot(redcap_final, aes(x = cancer_dx_code)) +
  geom_bar()

```
