---
title: "fetch_data: delivery encounter data (February 2025)"
author: "Dominick Lemas & Manoj Kambara"
date: "11/04/24"
output: html_document
---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview             
# **************************************************************************** #
# Author:            Dominick Lemas & Manoj Kambara
# Start Date:        Nov 04, 2024
# Last Modified:     Feb 18, 2025 
# IRB:         IRB protocol IRB201601899  
#
# Software Versions:
# - R version:       4.0.3 (2020-10-10)
# - RStudio version: 1.3.1073

# **************************************************************************** #
# ***************                Description                  
# **************************************************************************** #
# PLAN: Access flat files on sharedrive, pull/format/clean data for downstream.
# NOTE: vpn must be active
# OBJECTIVE: Export all delivery encounter data as rda file.  
```


```{r, message=FALSE}
# **************************************************************************** #
# ***************                Library                      
# **************************************************************************** #

# directory
working_dir="C:/Users/djlemas/OneDrive/Documents/ehr-database"

library(tidyverse)
library(devtools)
library(dplyr)
source(paste0(working_dir,"/code/functions/all_functions.R"))
# install.packages("gigs", repos = "https://ropensci.r-universe.dev")
library(gigs)        # Growth chart analysis


```

```{r, include=FALSE, message=FALSE, warning=FALSE}

# ----------------------------------------------------------------------- #
# Step 1: Pull Data
# ----------------------------------------------------------------------- #

# rows:            28530
# cols:            20 
# unique baby id:  28530
# repeat:          1
# ICD9/10:         NA

# column-types
#-------------
col_types <- readr::cols(
      Deidentified_mom_ID  = readr::col_factor(),
      race_infant = col_factor(),
      ethnicity_infant = col_factor(),
      date_of_delivery = col_factor(),
      birth_weight = col_double(),
      pediatric_delivery_type = col_factor(),
      admit_source = col_character(),
      pediatric_gestational_age = col_character(),
      sex = col_factor(),
      deidentified_mom_id = col_factor(),
      race_mom = col_factor(),
      ethnicity_mom = col_factor(),
      age_at_encounter_mom = col_double(),
      payer_mom = col_factor(),
      admit_date_mom = col_character(),
      admit_height_inches = col_double(),
      admit_weight_lbs = col_double(),
      admit_weight_kg = col_double(),
      admit_height_cm = col_double(),
      admit_bmi = col_double()
     )

# data-directory
#-----------------
data_dir=paste0("V:/FACULTY/DJLEMAS/EHR_Data/raw/READ_ONLY_DATASETS/10year_data/2021/dataset_09_2021/")
data_file_name="baby_mom_at_birth_with_payer.csv"
# data_dir=paste0("~/ehr-database/data/raw/dataset_09_2021/")
data_import_path=paste0(data_dir,data_file_name)

# read data
delivery_encounter_tmp=read_csv(data_import_path, col_types = col_types) %>%
  rename(part_id_mom_tmp=deidentified_mom_id,
         part_id_infant_tmp=deidentified_baby_id,
         sex_infant=sex,
         birth_weight_infant=birth_weight,
         delivery_type=pediatric_delivery_type,
         gestational_age_infant=pediatric_gestational_age,
         admit_height_inches_mom=admit_height_inches,
         age_at_delivery_mom=age_at_encounter_mom,
         admit_weight_lbs_mom=admit_weight_lbs,
         admit_weight_kg_mom=admit_weight_kg,
         admit_height_cm_mom=admit_height_cm,
         admit_bmi_mom=admit_bmi) %>%
  mutate(part_id_mom=paste0("mom-",part_id_mom_tmp),
         part_id_infant=paste0("infant-",part_id_infant_tmp)) %>%
  select(-part_id_mom_tmp, -part_id_infant_tmp) %>% 
  select(part_id_infant,part_id_mom, everything()) %>%
  mutate(part_dob_infant=mdy_hm(date_of_delivery),
         delivery_admit_date=mdy(admit_date_mom)) %>%
  select(-date_of_delivery,-admit_date_mom) %>%
  select(part_id_infant,part_id_mom,part_dob_infant,delivery_admit_date,everything()) %>%
  mutate(
    # Parse weeks and days
    gestational_age_parsed = map(gestational_age_infant, parse_gestational_age),
    gestational_age_weeks = map_dbl(gestational_age_parsed, "weeks"),
    gestational_age_days = map_dbl(gestational_age_parsed, "days"),
    # Calculate total gestational age in days
    gestational_age_days_total = (gestational_age_weeks * 7) + gestational_age_days,
    gestational_age_weeks_total = gestational_age_weeks + (gestational_age_days / 7)) %>%
  select(-gestational_age_parsed) %>%  # Remove intermediate column
  select(part_id_infant, part_id_mom, part_dob_infant, delivery_admit_date, race_infant, ethnicity_infant,
         birth_weight_infant, delivery_type, admit_source, gestational_age_infant, gestational_age_weeks_total, gestational_age_days_total, everything()) %>%
  select(-gestational_age_weeks, -gestational_age_days) %>%
  mutate(  # Recode maternal race and ethnicity to NIH-aligned categories
    race_mom_4grp = case_when(
      race_mom %in% c("HISPANIC", "WHITE HISPANIC") ~ "HISPANIC",
      race_mom == "AMERICAN INDIAN" ~ "NON-HISPANIC and AIAN",
      race_mom %in% c("ASIAN", "PACIFIC ISLANDER") ~ "ASIAN, OTHER",
      race_mom == "BLACK" ~ "NON-HISPANIC and BLACK",
      race_mom == "WHITE" ~ "NON-HISPANIC and WHITE",
      TRUE ~ "OTHER, UNSPECIFIED"
    ),
    ethnicity_mom = case_when(
      ethnicity_mom == "HISPANIC" ~ "Hispanic",
      ethnicity_mom == "NOT HISPANIC" ~ "Not Hispanic",
      TRUE ~ "Other, Unknown"
    )
  ) %>%  # Create Dummy Variables for Data Validation
  mutate(
    valid_admit_bmi = if_else(!is.na(admit_bmi_mom) & admit_bmi_mom > 10 & admit_bmi_mom < 80, 1, 0),
    valid_admit_weight_kg = if_else(!is.na(admit_weight_kg_mom) & admit_weight_kg_mom > 40, 1, 0),
    valid_height_cm = if_else(!is.na(admit_height_cm_mom) & admit_height_cm_mom > 93, 1, 0)
  ) %>%
  mutate(
    preterm_gestational_age = if_else(gestational_age_weeks_total <= 37, 1, 0),
    birth_wt_lbw = if_else(birth_weight_infant < 2500, 1, 0),
    cesarean_yes = if_else(grepl("C-Section", delivery_type, ignore.case = TRUE), 1, 0),
    sex_male = if_else(sex_infant == "MALE", 1, 0)
  ) %>%
  mutate(  # Categorize Gestational Age, Birth Weight, APGAR, and Infant Size
# Convert to character before passing to compute_sfga
    sex_infant = as.character(recode(sex_infant, "MALE" = "M", "FEMALE" = "F")),
    
    # Calculate size for gestational age
    size_for_ga_cat = compute_sfga(
      weight_kg = birth_weight_infant / 1000,
      gest_days = gestational_age_days_total,
      sex = sex_infant
    ),
    
    # Create dummy variables for size categories
    size_for_age_sga = if_else(size_for_ga_cat == "SGA", 1, 0),
    size_for_age_aga = if_else(size_for_ga_cat == "AGA", 1, 0),
    size_for_age_lga = if_else(size_for_ga_cat == "LGA", 1, 0)
  )
  
# END LOOP

```

```{r}

# ----------------------------------------------------------------------- #
# Step 2: load mom-baby link data
# ----------------------------------------------------------------------- #
load("V:/FACULTY/DJLEMAS/EHR_Data/processed/10year_data/mom_baby_link_02_2025.rda") 

mom_baby_link_tmp=mom_baby_link_02_2025 %>%
  select(part_id_infant, delivery_id)

# ----------------------------------------------------------------------- #
# Step 3: merge cancer data with mom-baby link and compute derived variables
# ----------------------------------------------------------------------- #
delivery_encounter_tmp2 =full_join(delivery_encounter_tmp, mom_baby_link_tmp, by = "part_id_infant") %>%
  select(part_id_infant,part_id_mom,delivery_id,everything())


# rename
delivery_encounter_02_2025=delivery_encounter_tmp2
```

```{r, message=FALSE}
# ----------------------------------------------------------------------- #
# Step 4: export to sharedrive
# ----------------------------------------------------------------------- #

## EXPORT 
file_name="delivery_encounter_02_2025.rda"
data_export_directory=paste0("V:/FACULTY/DJLEMAS/EHR_Data/processed/10year_data/") 
data_export_path=paste0(data_export_directory,file_name)
delivery_encounter_02_2025 %>% save(delivery_encounter_02_2025, file=data_export_path)
```

