---
title: "cancer data dictionary"
author: "Dominick Lemas"
date: "2023-11-20"
output: html_document
---

```{r, include=FALSE}
##-------------- 
# **************************************************************************** #
# ***************                Project Overview              *************** #
# **************************************************************************** #

# Author:            Dominick J. Lemas
# Start Date:        11/20/2023 
# Date Modify:       
# Project:           
# IRB:               
#                   
# R version 4.3.1 (2023-06-16 ucrt) -- "Beagle Scouts"
# Copyright (C) 2023 The R Foundation for Statistical Computing
# Platform: x86_64-w64-mingw32/x64 (64-bit)

# **************************************************************************** #
# ***************                Description                   *************** #
# **************************************************************************** #

# PLAN: check the cancer codes in data dictionary vs codes we have already requested



```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(tidyverse)
library(tibble)
library(ggplot2)
library(icd)

```


```{r setup, include=FALSE}

# cancer codes
#-------------
    # cancer=read_excel("E:/documents/ehr-database/documents/datadictionary/oneflorida/oneflorida_pregnancy_cancer_codes_10_2023.xlsx")

    cancer=read_excel("~/ehr-database/documents/datadictionary/oneflorida/oneflorida_pregnancy_cancer_codes_10_2023.xlsx") %>%
  rename(icd_short=Code)


```


```{r setup, include=FALSE}

load(file="V:/FACULTY/DJLEMAS/EHR_Data/raw/READ_ONLY_DATASETS/10year_data/analysis_ready/maternal_codes.RData")

# convert "decimal" --> "short" format
data_icd <- icdDxDecimalToShort(dxDataFile = maternal_codes,
                            icdColName = diagnosis_code,         
                            dateColName = diagnosis_start_date,
                            icd10usingDate = "2015/10/01")

# merge into data.frame
data_icd$ICD
maternal_codes_short=cbind(maternal_codes,data_icd$ICD) %>%
  rename(icd_short=ICD)


```

```{r setup, include=FALSE}

# unique cancer-codes from data-dictionary
cancer_codes_unique=unique(cancer$icd_short)
length(cancer_codes_unique)                    # 2132

# unique icd codes from data-raw
icd_codes_unique=unique(maternal_codes_short$icd_short)
length(icd_codes_unique)                       # 4996

# how many codes intersection?
length(intersect(cancer_codes_unique,icd_codes_unique))  # 502 intersect

# create match variable
cancer_match=cancer %>%
  mutate(match=ifelse((icd_short %in% icd_codes_unique), 1, 0))

# need to go through and match the codes we have already requested and expand new selection



```

```
